# Backend
backend = "glx";
vsync = true;

# Rounded corners (Windows 11 look)
corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'awesome'"
];

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.8;
fade-out-step = 0.4;

# General opacity
inactive-opacity = 1;
active-opacity = 1;

# App-specific opacity
opacity-rule = [
  "95:class_g = 'Alacritty'",
];

# Shadows (softer than Arch theme)
shadow = true;
shadow-radius = 20;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.5;
shadow-ignore-shaped = false;

shadow-exclude = [
  "class_g = 'Conky'",
  "class_g = 'Polybar'",
  "class_g = 'slop'",
  "name = 'Notification'",
  "class_g = 'awesome'",
  "_GTK_FRAME_EXTENTS@:c"
];
