#!/usr/bin/env bash
# Dotfiles installer entry point.
#
#   install.sh configure   # interactive questionnaire -> install.conf
#   install.sh plan        # dry-run: print every action, change nothing
#   install.sh install     # questionnaire (if needed) -> plan -> confirm -> run
#   install.sh <step>      # run a single step: yay|packages|drivers|services|stow|apps
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/lib.sh"

# ---- Questionnaire: write install.conf -----------------------------------
questionnaire() {
    log "Configuring your install. Press Enter to accept the [default]."
    load_config  # pre-seed defaults from any existing install.conf

    local gpu dm
    gpu="$(ask_str "GPU vendor (amd/intel/nvidia/hybrid)" "$(cfg GPU amd)")"
    dm="$(ask_str  "Display manager (lightdm/sddm/ly/none)" "$(cfg DISPLAY_MANAGER lightdm)")"

    local base dev virt media tex vscode browser claude lvm optional
    base="$(ask_yn    "Install base desktop apps (zathura, rofi, keepassxc, dolphin, flameshot, timeshift)?" "$([ "$(cfg INSTALL_BASE yes)"    = no ] && echo n || echo y)")"
    dev="$(ask_yn     "Install dev toolchains (docker, g++, java, python, ansible, kubernetes)?"             "$([ "$(cfg INSTALL_DEV yes)"     = no ] && echo n || echo y)")"
    virt="$(ask_yn    "Install virtualization (wine, virtualbox)?"                                          "$([ "$(cfg INSTALL_VIRT yes)"    = no ] && echo n || echo y)")"
    media="$(ask_yn   "Install media apps (obs, gimp, shotcut, kazam)?"                                     "$([ "$(cfg INSTALL_MEDIA yes)"   = no ] && echo n || echo y)")"
    tex="$(ask_yn     "Install TeX Live (LaTeX)?"                                                           "$([ "$(cfg INSTALL_TEXLIVE yes)" = no ] && echo n || echo y)")"
    vscode="$(ask_yn  "Install VSCode OSS (dark mode + LaTeX Workshop)?"                                    "$([ "$(cfg INSTALL_VSCODE yes)"  = no ] && echo n || echo y)")"
    browser="$(ask_yn "Install Brave browser (AUR)?"                                                        "$([ "$(cfg INSTALL_BROWSER yes)" = no ] && echo n || echo y)")"
    claude="$(ask_yn  "Install Claude Code CLI (AUR)?"                                                       "$([ "$(cfg INSTALL_CLAUDE yes)"  = no ] && echo n || echo y)")"
    lvm="$(ask_yn     "Install graphical LVM manager (kvpm, AUR)?"                                           "$([ "$(cfg INSTALL_LVM_GUI yes)" = no ] && echo n || echo y)")"
    optional="$(ask_yn "Try best-effort apps (Proton Drive, EuroOffice)?"                                   "$([ "$(cfg INSTALL_OPTIONAL no)" = yes ] && echo y || echo n)")"

    local clone_cv clone_goat video
    clone_cv="$(ask_yn   "Clone cv repo into ~/projects?"   "$([ "$(cfg CLONE_CV yes)"   = no ] && echo n || echo y)")"
    clone_goat="$(ask_yn "Clone goat repo into ~/projects (required by nvim)?" "$([ "$(cfg CLONE_GOAT yes)" = no ] && echo n || echo y)")"
    video="$(ask_yn      "Enable looping video wallpaper?"  "$([ "$(cfg VIDEO_WALLPAPER no)" = yes ] && echo y || echo n)")"

    cat > "$CONFIG_FILE" <<EOF
# Generated by install.sh configure
GPU=$gpu
DISPLAY_MANAGER=$dm
STOW_PACKAGES="$(cfg STOW_PACKAGES "awesome nvim tmux alacritty")"
THEMES="$(cfg THEMES "arch ubuntu windows7 win11")"
INSTALL_BASE=$base
INSTALL_DEV=$dev
INSTALL_VIRT=$virt
INSTALL_MEDIA=$media
INSTALL_TEXLIVE=$tex
INSTALL_VSCODE=$vscode
INSTALL_BROWSER=$browser
INSTALL_CLAUDE=$claude
INSTALL_LVM_GUI=$lvm
INSTALL_OPTIONAL=$optional
CLONE_CV=$clone_cv
CLONE_GOAT=$clone_goat
VIDEO_WALLPAPER=$video
EOF
    ok "Wrote $CONFIG_FILE"
}

# ---- Steps ----------------------------------------------------------------
run_all_steps() {
    bash "$HERE/yay-bootstrap.sh"
    bash "$HERE/packages.sh"
    bash "$HERE/drivers.sh"
    bash "$HERE/services.sh"
    bash "$HERE/stow.sh"
    bash "$HERE/apps.sh"
}

# Plan from install.conf, or from the example defaults if none exists yet.
plan() {
    if [ ! -f "$CONFIG_FILE" ]; then
        warn "No install.conf yet — planning from install.conf.example defaults."
        export CONFIG_FILE="$DOTFILES_DIR/install.conf.example"
    fi
    log "Planned actions (nothing will be changed):"
    DRY_RUN=1 run_all_steps
}

cmd_install() {
    require_arch
    [ -f "$CONFIG_FILE" ] || questionnaire
    echo
    plan
    echo
    if [ "$(ask_yn "Proceed with installation?" n)" != "yes" ]; then
        warn "Aborted. No changes made."
        exit 0
    fi
    run_all_steps
    ok "Done. Log out/in (or reboot) to apply group + display-manager changes."
}

case "${1:-install}" in
    configure) questionnaire ;;
    plan)      plan ;;
    install)   cmd_install ;;
    yay)       bash "$HERE/yay-bootstrap.sh" ;;
    packages)  bash "$HERE/packages.sh" ;;
    drivers)   bash "$HERE/drivers.sh" ;;
    services)  bash "$HERE/services.sh" ;;
    stow)      bash "$HERE/stow.sh" ;;
    apps)      bash "$HERE/apps.sh" ;;
    *)         err "Unknown command '$1'"; exit 1 ;;
esac
